name: EntityLibPlugin
version: 1.0.0
depend:
  - packetevents
main: me.tofaa.entitylib.EntityLibPlugin
api-version: 1.20
commands:
  testapi:
    description: Test PEEntityMeta API
    usage: /<command>

  testentity:
    description: Test PEEntity API
    usage: /<command>
  testdisplay:
    description: Test PEDisplay API
    usage: /<command>
  spawnclickablefrog:
    description: Spawn a clickable frog
    usage: /<command>