name: EntityLibPlugin
version: ${version}
depend:
  - packetevents
main: me.tofaa.testentitylib.TestEntityLibPlugin
api-version: "1.21"
commands:
  testapi:
    description: Test EntityLib API
    usage: /<command>